name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run lint
        run: |
          python -m pip install tox
          tox -e lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set git to use LF on Windows
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        if: runner.os != 'Windows'  # see issue #174
        with:
          python-version: 2.7
      - uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      # - name: Install Visual C++ for Python 2.7
      #   if: runner.os == 'Windows'
      #   run: choco install vcpython27 -f -y
      - name: Run tests on Windows  # see issue #174
        if: runner.os == 'Windows'
        run: |
          python -m pip install tox
          tox -e py35,py39
      - name: Run tests on Linux and macOS
        if: runner.os != 'Windows'
        run: |
          python -m pip install tox
          tox --skip-missing-interpreters

  package-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Build source package
        run: python setup.py sdist
      - name: Upload source package
        uses: actions/upload-artifact@v1
        with:
          name: sdist
          path: dist/

  package-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: manylinux
          os: ubuntu-latest
        - name: macos
          os: macos-latest
        - name: win
          os: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
    
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      # - name: Install Visual C++ for Python 2.7
      #   if: runner.os == 'Windows'
      #   run: choco install vcpython27 -f -y
      - name: Build wheels for Windows  # see issue #174
        if: runner.os == 'Windows'
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp35-${{ matrix.name }}* pp*-${{ matrix.name }}*
      - name: Build wheels for Linux and macOS
        if: runner.os != 'Windows'
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
          CIBW_ARCHS_LINUX: x86_64
      - uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.name }}
          path: ./wheelhouse/*.whl
  
  test-aarch64:
    name: "Test ${{ matrix.pyver }} aarch64"
    strategy:
      matrix:
        pyver: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39]
        arch: [aarch64]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_${{ matrix.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install tools
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
          ${{ env.img }} ${{ env.py }} -m pip install -U  pip build
    - name: Install dependencies
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} \
            bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
            source .env/bin/activate && \
            python -m pip install --upgrade pip && \
            deactivate'
    - name: Test with pytest
      run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} \
            bash -exc '\
            source .env/bin/activate && \
            pip install tox && \
            /opt/python/${{ matrix.pyver }}/bin/tox -e py && \
            tox --skip-missing-interpreters && \
            deactivate'
  
  build-aarch64:
    name: "Build wheels on aarch64"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
          
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel
      
    - name: Build wheels for Linux
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_ARCHS_LINUX: aarch64
        CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
      
    - uses: actions/upload-artifact@v2
      with:
        name: wheels-${{ matrix.name }}
        path: ./wheelhouse/*.whl
 
  publish:
    runs-on: ubuntu-latest
    needs: [lint, test, package-sdist, package-wheel]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: sdist
          path: dist/
      - uses: actions/download-artifact@v1
        with:
          name: wheels-win
          path: dist/
      - uses: actions/download-artifact@v1
        with:
          name: wheels-macos
          path: dist/
      - uses: actions/download-artifact@v1
        with:
          name: wheels-manylinux
          path: dist/
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
